apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-api
  namespace: staff-manager
  labels:
    app: sm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm-api
  template:
    metadata:
      labels:
        app: sm-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
{{/*      serviceAccountName: sm-api*/}}
      containers:
        - name: sm-api
          imagePullPolicy: Always
          image: mchekini/sm-api:1.0
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAS7WDEOQ4IJEOYB67"
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: AWS_SECRET_ACCESS_KEY
              value: "DUd3Q+F3vWtmH3OspGKYlZ75+F7mTIJarwAUj9kC"
            - name: kubeVersion
              value: "3.0.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /api/v1/health
              httpHeaders:
                - name: header1
                  value: "sm-header"
              port: 8080
            initialDelaySeconds: 20
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 20
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
