apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-api
  labels:
    app: sm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm-api
  template:
    metadata:
      name: sm-api
      labels:
        app: sm-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - name: sm-api
          image: mchekini/sm-api:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DEPLOYMENT_VERSION
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: aws-secret-key
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/health
              httpHeaders:
                - name: header1
                  value: neymar
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/health
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              port: 8080
              path: /api/v1/health
            successThreshold: 1
            failureThreshold: 6
            initialDelaySeconds: 10
