apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-api
  namespace: staff-manager
  labels:
    app: sm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-api
  template:
    metadata:
      labels:
        app: sm-api
    spec:
{{/*      serviceAccountName: sm-api*/}}
      containers:
        - name: sm-api
          imagePullPolicy: Always
          image: mchekini/sm-api:1.0
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAS7WDEOQ4EJUQXRA4"
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: AWS_SECRET_ACCESS_KEY
              value: "lrPBp5TL6Jwgvysl241yNDpwmUnHLYrTS/SU67Od"
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /api/v1/health*/}}
{{/*              port: 8080*/}}
{{/*            initialDelaySeconds: 20*/}}
{{/*            successThreshold: 1*/}}
{{/*            failureThreshold: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /api/v1/health*/}}
{{/*              port: 8080*/}}
{{/*            initialDelaySeconds: 20*/}}
{{/*            successThreshold: 1*/}}
{{/*            failureThreshold: 5*/}}
{{/*            periodSeconds: 10*/}}
