apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sm-api
spec:
  ingressClassName: nginx
  rules:
    - host: api.check-consulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sm-api
                port:
                  number: 8080