spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://qua-staff-manager-db.chqar689pasc.us-east-2.rds.amazonaws.com:5432/postgres
    username: sm-qua-db-creds
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver



bucket:
  justificatifs: qua-justificatifs-check-consulting
  fiche-de-paie: qua-fiche-de-paie-check-consulting
  factures: qua-factures-check-consulting